### ISSUE TITLE
Не срабатывает Connect Points

### ISSUE THREAD

**Issue by cybergeo82** [nextgis/qgis.connect_points#4]
В интерфейсе QGIS у модуля два функции:
1. Настройка полей для соединения точек 
2. Запуск модуля

Настройка полей не открывается, выдаётся ошибка: 

An error has occurred while executing Python code: 

AttributeError: 'builtin_function_or_method' object has no attribute 'messageBar' 
Traceback (most recent call last):
  File "C:\Users/Cybergeo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\connect_points\qgis_connect_points.py", line 96, in showSettings
    dlg = Dialog(
  File "C:\Users/Cybergeo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\connect_points\dialog.py", line 164, in __init__
    self.fillControls(
  File "C:\Users/Cybergeo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\connect_points\dialog.py", line 190, in fillControls
    layerFrom = self.getQGISLayer(curPointsLayerFrom)
  File "C:\Users/Cybergeo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\connect_points\dialog.py", line 235, in getQGISLayer
    QgisPlugin(iface=self.parent).showMessageForUser(
  File "C:\Users/Cybergeo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\connect_points\qgis_plugin.py", line 82, in showMessageForUser
    self._iface.messageBar().pushMessage(
AttributeError: 'builtin_function_or_method' object has no attribute 'messageBar'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.7-Białowieża Białowieża, 5a65627a 

Python Path:
C:/PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python
C:/Users/Cybergeo/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Cybergeo/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.7/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.7\bin\python39.zip
C:\PROGRA~1\QGIS32~1.7\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib
C:\Program Files\QGIS 3.22.7\bin
C:\PROGRA~1\QGIS32~1.7\apps\Python39
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\GDAL-3.4.3-py3.9-win-amd64.egg
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.7\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Cybergeo/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by simgislab** [comment]
в QGIS 3.24 и NGQ работает без проблем, меню настроек открывается без ошибок

Подозрительная точка в имени папки QGIS321.7

**Comment by cybergeo82** [comment]
Странно. Сегодня всё сработало штатно и в QGIS 3, и в NextGIS QGIS. Ничего не менял.

Наверное можно закрыть эту тему.
